// AUTO-GENERATED by scripts/generateWrappers.ts — do not edit.

export { VehicleTypeForm } from './vehicleType';
export type { VehicleTypeFormProps } from './vehicleType';
export { VehicleForm } from './vehicle';
export type { VehicleFormProps } from './vehicle';
