// AUTO-GENERATED by scripts/generateWrappers.ts — do not edit.

import { createAbstractEntityDetailsForm } from '../abstractForm';
import { useEntityForm } from '../hooks/useEntityForm';
import { FIELDS } from '../../entities/vehicle';
import type { Entity as Vehicle } from '../../entities/vehicle';
import { GetVehicleDocument, UpdateVehicleDocument } from '../../generated/operations/vehicle.generated';
import type { EntityDetailsFormProps } from '../types';

const VehicleFormPresentation = createAbstractEntityDetailsForm<Vehicle>(FIELDS);

export interface VehicleFormProps
  extends Omit<EntityDetailsFormProps<Vehicle>, 'value' | 'onChange' | 'mode' | 'errors' | 'disabled'> {
  endpoint: string;
  headers?: Record<string, string>;
  getHeaders?: () => Record<string, string> | Promise<Record<string, string>>;
  netexId?: string;
  mode?: 'view' | 'edit';
  onSaved?: (netexId: string) => void;
  onError?: (generalErrors: string[]) => void;
}

export function VehicleForm(props: VehicleFormProps) {
  const { mode = 'edit', layout, variant, slotProps, ...rest } = props;
  const { value, setValue, loading, saving, errors, handleSave } = useEntityForm<Vehicle>({
    fields: FIELDS,
    query: {
      document: GetVehicleDocument,
      variables: (netexId) => ({ filter: { netexIds: [netexId], dataOwnerRef: '' } }),
      resultPath: ['vehicles', 'content', 0] as const,
    },
    mutation: {
      document: UpdateVehicleDocument,
      resultPath: ['createOrUpdateVehicle'] as const,
    },
    ...rest,
  });

  if (loading && !value) return <div>Loading...</div>;

  return (
    <>
      <VehicleFormPresentation
        value={value ?? ({} as Vehicle)}
        onChange={setValue}
        mode={mode}
        layout={layout}
        variant={variant}
        slotProps={slotProps}
        errors={errors}
        disabled={loading || saving}
      />
      {mode === 'edit' && (
        <button onClick={handleSave} disabled={saving}>Save</button>
      )}
    </>
  );
}
