// AUTO-GENERATED by scripts/generateWrappers.ts — do not edit.

import { createAbstractEntityDetailsForm } from '../abstractForm';
import { useEntityForm } from '../hooks/useEntityForm';
import { FIELDS } from '../../entities/vehicleType';
import type { Entity as VehicleType } from '../../entities/vehicleType';
import { GetVehicleTypeDocument, UpdateVehicleTypeDocument } from '../../generated/operations/vehicleType.generated';
import type { EntityDetailsFormProps } from '../types';

const VehicleTypeFormPresentation = createAbstractEntityDetailsForm<VehicleType>(FIELDS);

export interface VehicleTypeFormProps
  extends Omit<EntityDetailsFormProps<VehicleType>, 'value' | 'onChange' | 'mode' | 'errors' | 'disabled'> {
  endpoint: string;
  headers?: Record<string, string>;
  getHeaders?: () => Record<string, string> | Promise<Record<string, string>>;
  netexId?: string;
  mode?: 'view' | 'edit';
  onSaved?: (netexId: string) => void;
  onError?: (generalErrors: string[]) => void;
}

export function VehicleTypeForm(props: VehicleTypeFormProps) {
  const { mode = 'edit', layout, variant, slotProps, ...rest } = props;
  const { value, setValue, loading, saving, errors, handleSave } = useEntityForm<VehicleType>({
    fields: FIELDS,
    query: {
      document: GetVehicleTypeDocument,
      variables: (netexId) => ({ filter: { netexIds: [netexId], dataOwnerRef: '' } }),
      resultPath: ['vehicleTypes', 'content', 0] as const,
    },
    mutation: {
      document: UpdateVehicleTypeDocument,
      resultPath: ['createOrUpdateVehicleType'] as const,
    },
    ...rest,
  });

  if (loading && !value) return <div>Loading...</div>;

  return (
    <>
      <VehicleTypeFormPresentation
        value={value ?? ({} as VehicleType)}
        onChange={setValue}
        mode={mode}
        layout={layout}
        variant={variant}
        slotProps={slotProps}
        errors={errors}
        disabled={loading || saving}
      />
      {mode === 'edit' && (
        <button onClick={handleSave} disabled={saving}>Save</button>
      )}
    </>
  );
}
