// AUTO-GENERATED by scripts/distillTypes.ts — do not edit.
// Distilled from VehicleType (full read type); write boundary from VehicleTypeInput.
import type { DeckPlan, KeyValues, Maybe, MultilingualString, PassengerCapacity, PrivateCode, Scalars, Vehicle } from '../generated/sobekTypes';
import { FareClass, FuelType, HybridCategory, PropulsionType, TransportMode } from '../generated/sobekTypes';
import type { FieldSpec, Layout as LibLayout } from '../EntityDetailsForm/types';
/** The value shape — the full read entity, nested structure preserved. */
export interface Entity {
  carLoading?: Maybe<Scalars['Boolean']['output']>;
  changed?: Maybe<Scalars['DateTime']['output']>;
  changedBy?: Maybe<Scalars['String']['output']>;
  created?: Maybe<Scalars['DateTime']['output']>;
  dataOwnerRef?: Maybe<Scalars['String']['output']>;
  deckPlan?: Maybe<DeckPlan>;
  description?: Maybe<MultilingualString>;
  euroClass?: Maybe<Scalars['String']['output']>;
  formDragCoefficient?: Maybe<Scalars['Float']['output']>;
  fuelTypes?: Maybe<Array<Maybe<FuelType>>>;
  fullCharge?: Maybe<Scalars['Float']['output']>;
  height?: Maybe<Scalars['Float']['output']>;
  hybridCategory?: Maybe<HybridCategory>;
  keyValues?: Maybe<Array<KeyValues>>;
  length?: Maybe<Scalars['Float']['output']>;
  lowFloor?: Maybe<Scalars['Boolean']['output']>;
  manufacturer?: Maybe<Scalars['String']['output']>;
  maximumEngineEffectKW?: Maybe<Scalars['Float']['output']>;
  maximumRange?: Maybe<Scalars['Float']['output']>;
  maximumVelocity?: Maybe<Scalars['Float']['output']>;
  name?: Maybe<MultilingualString>;
  netexId: Scalars['String']['output'];
  passengerCapacity?: Maybe<PassengerCapacity>;
  privateCode?: Maybe<PrivateCode>;
  propulsionTypes?: Maybe<Array<Maybe<PropulsionType>>>;
  range?: Maybe<Scalars['Float']['output']>;
  rollResistanceCoefficient?: Maybe<Scalars['Float']['output']>;
  selfPropelled?: Maybe<Scalars['Boolean']['output']>;
  shortName?: Maybe<MultilingualString>;
  transportMode?: Maybe<TransportMode>;
  vehicles?: Maybe<Array<Vehicle>>;
  version?: Maybe<Scalars['String']['output']>;
  weight?: Maybe<Scalars['Float']['output']>;
  width?: Maybe<Scalars['Float']['output']>;
}
/** Flat, addressable field registry — value-object leaves hoisted, each with a path. */
export const FIELDS = {
  carLoading: { kind: 'switch', path: ['carLoading'] },
  changed: { kind: 'datetime', path: ['changed'], serverManaged: true },
  changedBy: { kind: 'text', path: ['changedBy'], serverManaged: true },
  created: { kind: 'datetime', path: ['created'], serverManaged: true },
  dataOwnerRef: { kind: 'text', path: ['dataOwnerRef'] },
  deckPlan: { kind: 'reference', path: ['deckPlan', 'netexId'] },
  description: { kind: 'name', path: ['description'] },
  euroClass: { kind: 'text', path: ['euroClass'] },
  formDragCoefficient: { kind: 'number', path: ['formDragCoefficient'] },
  fuelTypes: { kind: 'enumMulti', path: ['fuelTypes'], options: Object.values(FuelType) },
  fullCharge: { kind: 'number', path: ['fullCharge'] },
  height: { kind: 'number', path: ['height'] },
  hybridCategory: { kind: 'enum', path: ['hybridCategory'], options: Object.values(HybridCategory) },
  length: { kind: 'number', path: ['length'] },
  lowFloor: { kind: 'switch', path: ['lowFloor'] },
  manufacturer: { kind: 'text', path: ['manufacturer'] },
  maximumEngineEffectKW: { kind: 'number', path: ['maximumEngineEffectKW'] },
  maximumRange: { kind: 'number', path: ['maximumRange'] },
  maximumVelocity: { kind: 'number', path: ['maximumVelocity'] },
  name: { kind: 'name', path: ['name'] },
  netexId: { kind: 'text', path: ['netexId'] },
  bicycleRackCapacity: { kind: 'number', path: ['passengerCapacity', 'bicycleRackCapacity'] },
  fareClass: { kind: 'enum', path: ['passengerCapacity', 'fareClass'], options: Object.values(FareClass) },
  pramPlaceCapacity: { kind: 'number', path: ['passengerCapacity', 'pramPlaceCapacity'] },
  pushchairCapacity: { kind: 'number', path: ['passengerCapacity', 'pushchairCapacity'] },
  seatingCapacity: { kind: 'number', path: ['passengerCapacity', 'seatingCapacity'] },
  specialPlaceCapacity: { kind: 'number', path: ['passengerCapacity', 'specialPlaceCapacity'] },
  standingCapacity: { kind: 'number', path: ['passengerCapacity', 'standingCapacity'] },
  totalCapacity: { kind: 'number', path: ['passengerCapacity', 'totalCapacity'] },
  wheelchairPlaceCapacity: { kind: 'number', path: ['passengerCapacity', 'wheelchairPlaceCapacity'] },
  type: { kind: 'text', path: ['privateCode', 'type'] },
  value: { kind: 'text', path: ['privateCode', 'value'] },
  propulsionTypes: { kind: 'enumMulti', path: ['propulsionTypes'], options: Object.values(PropulsionType) },
  range: { kind: 'number', path: ['range'] },
  rollResistanceCoefficient: { kind: 'number', path: ['rollResistanceCoefficient'] },
  selfPropelled: { kind: 'switch', path: ['selfPropelled'] },
  shortName: { kind: 'name', path: ['shortName'] },
  transportMode: { kind: 'enum', path: ['transportMode'], options: Object.values(TransportMode) },
  vehicles: { kind: 'grid', path: ['vehicles'], serverManaged: true },
  version: { kind: 'text', path: ['version'], serverManaged: true },
  weight: { kind: 'number', path: ['weight'] },
  width: { kind: 'number', path: ['width'] },
} satisfies Record<string, FieldSpec>;
export type EntityField = keyof typeof FIELDS;
export type EntityLayout = LibLayout<EntityField>;