// AUTO-GENERATED by scripts/distillTypes.ts — do not edit.
// Distilled from Vehicle (full read type); write boundary from VehicleInput.
import type { Maybe, MultilingualString, Scalars, VehicleType } from '../generated/sobekTypes';
import type { FieldSpec, Layout as LibLayout } from '../EntityDetailsForm/types';
/** The value shape — the full read entity, nested structure preserved. */
export interface Entity {
  buildDate?: Maybe<Scalars['Date']['output']>;
  changed?: Maybe<Scalars['DateTime']['output']>;
  changedBy?: Maybe<Scalars['String']['output']>;
  chassisNumber?: Maybe<Scalars['String']['output']>;
  created?: Maybe<Scalars['DateTime']['output']>;
  dataOwnerRef?: Maybe<Scalars['String']['output']>;
  description?: Maybe<MultilingualString>;
  name?: Maybe<MultilingualString>;
  netexId: Scalars['String']['output'];
  operationalNumber?: Maybe<Scalars['String']['output']>;
  registrationDate?: Maybe<Scalars['Date']['output']>;
  registrationNumber?: Maybe<Scalars['String']['output']>;
  transportType?: Maybe<VehicleType>;
  version?: Maybe<Scalars['String']['output']>;
}
/** Flat, addressable field registry — value-object leaves hoisted, each with a path. */
export const FIELDS = {
  buildDate: { kind: 'text', path: ['buildDate'] },
  changed: { kind: 'text', path: ['changed'], serverManaged: true },
  changedBy: { kind: 'text', path: ['changedBy'], serverManaged: true },
  chassisNumber: { kind: 'text', path: ['chassisNumber'] },
  created: { kind: 'text', path: ['created'], serverManaged: true },
  dataOwnerRef: { kind: 'text', path: ['dataOwnerRef'] },
  description: { kind: 'name', path: ['description'] },
  name: { kind: 'name', path: ['name'] },
  netexId: { kind: 'text', path: ['netexId'] },
  operationalNumber: { kind: 'text', path: ['operationalNumber'] },
  registrationDate: { kind: 'text', path: ['registrationDate'] },
  registrationNumber: { kind: 'text', path: ['registrationNumber'] },
  version: { kind: 'text', path: ['version'], serverManaged: true },
} satisfies Record<string, FieldSpec>;
export type EntityField = keyof typeof FIELDS;
export type EntityLayout = LibLayout<EntityField>;