/**
 * distillTypes — compile-time step (runs after codegen, before build/test).
 *
 * For each manifest entry it parses `src/generated/sobekTypes.ts` with the
 * TypeScript compiler API and emits a committed `src/entities/<entity>.ts`
 * carrying:
 *   - `interface Entity` — the FULL read type, verbatim.
 *   - `const FIELDS`     — a flat control-kind registry (value-objects flattened
 *                          to leaves; relations & unsupported types omitted).
 * Plus a barrel `src/entities/index.ts` aliasing each entity for the public API.
 *
 * Governing assumption: `Input`'s field set ⊆ `Entity`'s. A write-only field
 * (in Input, not Entity) aborts the run — fix via `schema/sobek.patch.graphqls`.
 */
import ts from 'typescript';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/* ------------------------------------------------------------------ *\
   Constants
\* ------------------------------------------------------------------ */

const GENERATED = 'src/generated/sobekTypes.ts';
const MANIFEST = 'entities.manifest.json';
const OUT_DIR = 'src/entities';
const GEN_IMPORT = '../generated/sobekTypes';
const TYPES_IMPORT = '../EntityDetailsForm/types';
const MLS = 'MultilingualString'; // edited via the `name` control, never flattened
const IDENTITY = new Set(['id', 'netexId']); // an object with one of these is a relation

/** GraphQL scalar → control kind (codegen names; unknown scalars fall back to text). */
const SCALAR_KIND: Record<string, 'text' | 'number' | 'switch' | 'date' | 'datetime'> = {
  Boolean: 'switch',
  Int: 'number',
  Float: 'number',
  Long: 'number',
  String: 'text',
  ID: 'text',
  DateTime: 'datetime', // native <input type=datetime-local>
  Date: 'date', // native <input type=date>
};

const BANNER = '// AUTO-GENERATED by scripts/distillTypes.ts — do not edit.';

/* ------------------------------------------------------------------ *\
   Parse model
\* ------------------------------------------------------------------ */

interface Model {
  objects: Map<string, ts.TypeLiteralNode>; // type X = { ... }
  enums: Set<string>;
  exported: Set<string>; // all importable names from the generated module
}

const parseModel = (src: string): Model => {
  const sf = ts.createSourceFile('sobekTypes.ts', src, ts.ScriptTarget.Latest, true);
  const objects = new Map<string, ts.TypeLiteralNode>();
  const enums = new Set<string>();
  const exported = new Set<string>();
  sf.forEachChild(node => {
    if (ts.isTypeAliasDeclaration(node)) {
      exported.add(node.name.text);
      if (ts.isTypeLiteralNode(node.type)) objects.set(node.name.text, node.type);
    } else if (ts.isEnumDeclaration(node)) {
      exported.add(node.name.text);
      enums.add(node.name.text);
    }
  });
  return { objects, enums, exported };
};

/* ------------------------------------------------------------------ *\
   Type resolution
\* ------------------------------------------------------------------ */

interface Resolved {
  scalar?: string; // e.g. 'String'
  enum?: string; // enum name
  object?: string; // object type name
  isArray: boolean;
}

/** Unwrap Maybe<>/Array<>/IndexedAccess to a base descriptor. */
const resolveType = (node: ts.TypeNode, model: Model): Resolved => {
  let isArray = false;
  let cur: ts.TypeNode | undefined = node;
  while (cur) {
    if (ts.isTypeReferenceNode(cur)) {
      const name = cur.typeName.getText();
      if (name === 'Maybe' || name === 'InputMaybe' || name === 'Array') {
        if (name === 'Array') isArray = true;
        cur = cur.typeArguments?.[0];
        continue;
      }
      if (model.enums.has(name)) return { enum: name, isArray };
      if (model.objects.has(name) || model.exported.has(name)) return { object: name, isArray };
      return { isArray }; // unknown reference → unsupported
    }
    if (ts.isIndexedAccessTypeNode(cur)) {
      // Scalars['Foo']['output'] → 'Foo'
      const obj = cur.objectType;
      if (ts.isIndexedAccessTypeNode(obj) && ts.isLiteralTypeNode(obj.indexType)) {
        return { scalar: obj.indexType.literal.getText().replace(/'/g, ''), isArray };
      }
      return { isArray };
    }
    if (ts.isArrayTypeNode(cur)) {
      isArray = true;
      cur = cur.elementType;
      continue;
    }
    return { isArray };
  }
  return { isArray };
};

/* ------------------------------------------------------------------ *\
   Field derivation
\* ------------------------------------------------------------------ */

interface FieldOut {
  key: string;
  kind: string;
  path: string[];
  optionEnum?: string;
  serverManaged?: boolean;
}

const hasIdentity = (lit: ts.TypeLiteralNode): boolean =>
  lit.members.some(m => ts.isPropertySignature(m) && IDENTITY.has(m.name.getText()));

/**
 * Reference divergence: the read field is a single identity-object (a relation
 * normally omitted), but the same-named Input field is a *pure reference* — an
 * object whose every member is an identity key (e.g. `VehicleTypeReferenceInput
 * { netexId }`). Such a field IS writable (as a ref), so surface it as an
 * editable `reference` control bound to the identity leaf.
 *
 * @returns The identity leaf to target (present on both read + ref objects), or
 *          `undefined` when this is not a read-object/write-reference pair.
 */
const refLeaf = (
  readType: ts.TypeNode,
  inpType: ts.TypeNode | undefined,
  model: Model
): string | undefined => {
  if (!inpType) return undefined;
  const r = resolveType(readType, model);
  if (r.isArray || !r.object || r.object === MLS) return undefined;
  const readLit = model.objects.get(r.object);
  if (!readLit || !hasIdentity(readLit)) return undefined; // read must be a relation

  const i = resolveType(inpType, model);
  if (i.isArray || !i.object) return undefined;
  const inpLit = model.objects.get(i.object);
  if (!inpLit) return undefined;
  const inpKeys = [...members(inpLit).keys()];
  // Pure reference: non-empty and every member is an identity key.
  if (!inpKeys.length || !inpKeys.every(k => IDENTITY.has(k))) return undefined;

  const readKeys = members(readLit);
  return inpKeys.find(k => readKeys.has(k)) ?? inpKeys[0];
};

/** Member name → its type node, for a TypeLiteral. */
const members = (lit: ts.TypeLiteralNode): Map<string, ts.TypeNode> => {
  const out = new Map<string, ts.TypeNode>();
  lit.members.forEach(m => {
    if (ts.isPropertySignature(m) && m.type) out.set(m.name.getText(), m.type);
  });
  return out;
};

/** Register a field key, throwing on collision across the flat key space. */
const push = (taken: Set<string>, f: FieldOut): FieldOut => {
  if (taken.has(f.key))
    throw new Error(`distillTypes: duplicate field key "${f.key}" (path ${f.path.join('.')})`);
  taken.add(f.key);
  return f;
};

/**
 * Walk a read field into zero or more `FieldOut` entries.
 * - scalar/enum/boolean → one field; enum-array → enumMulti.
 * - MultilingualString → `name` control.
 * - id-less value-object → recurse (flatten); leaf collisions throw.
 * - array of identity objects → one `grid` field (read-only; carries serverManaged).
 * - single relation / id-less object array / unsupported → omitted (return []).
 */
const deriveFields = (
  name: string,
  type: ts.TypeNode,
  model: Model,
  path: string[],
  serverManaged: boolean,
  taken: Set<string>
): FieldOut[] => {
  const r = resolveType(type, model);
  const here = [...path, name];

  if (r.enum) {
    const kind = r.isArray ? 'enumMulti' : 'enum';
    return [push(taken, { key: name, kind, path: here, optionEnum: r.enum, serverManaged })];
  }
  if (r.scalar) {
    return [
      push(taken, { key: name, kind: SCALAR_KIND[r.scalar] ?? 'text', path: here, serverManaged }),
    ];
  }
  if (r.object) {
    if (r.object === MLS)
      return [push(taken, { key: name, kind: 'name', path: here, serverManaged })];
    const lit = model.objects.get(r.object);
    if (!lit) return []; // unknown object → omit (round-trips on Entity)
    // Array of linked entities → read-only grid. `serverManaged` is the flag the
    // caller already derived from the Input boundary (relations are absent from
    // Input, so this lands true) — not hand-tagged downstream.
    if (r.isArray && hasIdentity(lit))
      return [push(taken, { key: name, kind: 'grid', path: here, serverManaged })];
    if (hasIdentity(lit)) return []; // single relation → no flat control; omit
    if (r.isArray) return []; // identity-less object array → omit
    // value-object → flatten leaves
    return [...members(lit)].flatMap(([leaf, leafType]) =>
      deriveFields(leaf, leafType, model, here, serverManaged, taken)
    );
  }
  return []; // unsupported → omit (round-trips on Entity)
};

/* ------------------------------------------------------------------ *\
   Emit
\* ------------------------------------------------------------------ */

/** Collect TypeReference identifier names used in a type node (for imports). */
const refNames = (node: ts.TypeNode, acc: Set<string>): void => {
  const visit = (n: ts.Node): void => {
    if (ts.isTypeReferenceNode(n)) acc.add(n.typeName.getText());
    n.forEachChild(visit);
  };
  visit(node);
};

const camel = (s: string): string => s.charAt(0).toLowerCase() + s.slice(1);

/**
 * Distill one read/write pair into an entity-module source string.
 * @throws if a write-only field (in `inpEntity`, not `entity`) is found.
 */
export function distillModule(src: string, entity: string, inpEntity: string): string {
  const model = parseModel(src);
  const lit = model.objects.get(entity);
  const inpLit = model.objects.get(inpEntity);
  if (!lit) throw new Error(`distillTypes: read type "${entity}" not found`);
  if (!inpLit) throw new Error(`distillTypes: input type "${inpEntity}" not found`);

  const readMembers = members(lit);
  const inpMembers = members(inpLit);
  const inpNames = new Set(inpMembers.keys());

  // Subset assumption: every Input field must exist on Entity.
  const writeOnly = [...inpNames].filter(n => !readMembers.has(n));
  if (writeOnly.length) {
    throw new Error(
      `distillTypes: ${inpEntity}.${writeOnly.join(', ')} has no ${entity} counterpart — ` +
        `add \`extend type ${entity} { ${writeOnly[0]}: ... }\` to schema/sobek.patch.graphqls`
    );
  }

  // FIELDS, in read-schema member order.
  const taken = new Set<string>();
  const fields: FieldOut[] = [];
  for (const [name, type] of readMembers) {
    const serverManaged = !inpNames.has(name);
    // Writable relation written as a pure reference → editable `reference` field
    // on the identity leaf (read side would otherwise omit it as a relation).
    const leaf = serverManaged ? undefined : refLeaf(type, inpMembers.get(name), model);
    if (leaf) {
      fields.push(push(taken, { key: name, kind: 'reference', path: [name, leaf] }));
      continue;
    }
    fields.push(...deriveFields(name, type, model, [], serverManaged, taken));
  }

  // Verbatim interface members + referenced type names.
  const refs = new Set<string>();
  const memberLines = lit.members.filter(ts.isPropertySignature).map(m => {
    if (m.type) refNames(m.type, refs);
    return '  ' + m.getText().replace(/;?\s*$/, '') + ';';
  });

  // Imports: enum value-imports (used in interface or as FIELDS options) vs type-imports.
  const optionEnums = new Set(fields.map(f => f.optionEnum).filter(Boolean) as string[]);
  const valueImports = new Set<string>();
  const typeImports = new Set<string>();
  for (const name of [...refs, ...optionEnums]) {
    if (name === entity || name === inpEntity) continue; // never import self
    if (!model.exported.has(name)) continue; // built-ins (Array, etc.)
    if (model.enums.has(name)) valueImports.add(name);
    else typeImports.add(name);
  }

  const fieldLine = (f: FieldOut): string => {
    const parts = [`kind: '${f.kind}'`, `path: [${f.path.map(p => `'${p}'`).join(', ')}]`];
    if (f.optionEnum) parts.push(`options: Object.values(${f.optionEnum})`);
    if (f.serverManaged) parts.push('serverManaged: true');
    return `  ${f.key}: { ${parts.join(', ')} },`;
  };

  return [
    BANNER,
    `// Distilled from ${entity} (full read type); write boundary from ${inpEntity}.`,
    typeImports.size
      ? `import type { ${[...typeImports].sort().join(', ')} } from '${GEN_IMPORT}';`
      : '',
    valueImports.size
      ? `import { ${[...valueImports].sort().join(', ')} } from '${GEN_IMPORT}';`
      : '',
    `import type { FieldSpec, Layout as LibLayout } from '${TYPES_IMPORT}';`,
    '',
    '/** The value shape — the full read entity, nested structure preserved. */',
    'export interface Entity {',
    ...memberLines,
    '}',
    '',
    '/** Flat, addressable field registry — value-object leaves hoisted, each with a path. */',
    'export const FIELDS = {',
    ...fields.map(fieldLine),
    '} satisfies Record<string, FieldSpec>;',
    '',
    'export type EntityField = keyof typeof FIELDS;',
    'export type EntityLayout = LibLayout<EntityField>;',
    '',
  ]
    .filter(line => line !== '')
    .join('\n');
}

/* ------------------------------------------------------------------ *\
   Barrel + main
\* ------------------------------------------------------------------ */

interface Row {
  entity: string;
  inpEntity: string;
  file: string; // camel(entity)
  as: string;
}

/** Normalize a manifest entry (string or override object) to a Row. */
const toRow = (entry: string | { entity: string; inpEntity?: string; as?: string }): Row => {
  const e = typeof entry === 'string' ? { entity: entry } : entry;
  return {
    entity: e.entity,
    inpEntity: (e as { inpEntity?: string }).inpEntity ?? `${e.entity}Input`,
    file: camel(e.entity),
    as: (e as { as?: string }).as ?? e.entity,
  };
};

const buildBarrel = (rows: Row[]): string =>
  [
    BANNER,
    ...rows.flatMap(r => [
      `export type { Entity as ${r.as}, EntityLayout as ${r.as}Layout } from './${r.file}';`,
      `export { FIELDS as ${camel(r.as)}Fields } from './${r.file}';`,
    ]),
    '',
  ].join('\n');

const main = (): void => {
  const src = readFileSync(resolve(GENERATED), 'utf8');
  const manifest: (string | { entity: string })[] = JSON.parse(
    readFileSync(resolve(MANIFEST), 'utf8')
  );
  const rows = manifest.map(toRow);
  for (const r of rows) {
    const out = distillModule(src, r.entity, r.inpEntity);
    const path = resolve(OUT_DIR, `${r.file}.ts`);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, out);
    console.log(`[distill] ${r.entity} ∩ ${r.inpEntity} → ${OUT_DIR}/${r.file}.ts`);
  }
  writeFileSync(resolve(OUT_DIR, 'index.ts'), buildBarrel(rows));
  console.log(`[distill] wrote ${OUT_DIR}/index.ts (${rows.length} entities)`);
};

// Run as a script (not when imported by tests).
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    main();
  } catch (err) {
    console.error(String(err instanceof Error ? err.message : err));
    process.exit(1);
  }
}
