/**
 * generateWrappers — compile-time step.
 *
 * For each manifest entry it reads the committed entity file for `FIELDS` and
 * the generated operation file for document names, then writes a thin
 * `src/EntityDetailsForm/formImpls/<entity>.tsx` smart wrapper component.
 *
 * Manifest policy in `entities.manifest.json` also drives the query root name
 * and the mutation result field so the wrapper stays correct when the naming
 * diverges from `createOrUpdate<Entity>`.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const MANIFEST = 'entities.manifest.json';
const OUT_DIR = 'src/EntityDetailsForm/formImpls';
const BANNER = '// AUTO-GENERATED by scripts/generateWrappers.ts — do not edit.\n';

const toCamel = (s: string) => s.charAt(0).toLowerCase() + s.slice(1);

interface ManifestEntry {
  entity: string;
  queryRoot: string;
  mutationName: string;
  ignore?: string[];
  relationFields?: string[];
}

const main = (): void => {
  const manifest: ManifestEntry[] = JSON.parse(readFileSync(resolve(MANIFEST), 'utf8'));
  mkdirSync(resolve(OUT_DIR), { recursive: true });

  const exports: string[] = [];

  for (const entry of manifest) {
    const entityName = entry.entity;
    const fileName = toCamel(entityName);
    const compName = `${entityName}Form`;

    const getDoc = `Get${entityName}Document`;
    const updateDoc = `Update${entityName}Document`;

    const src = [
      BANNER,
      `import { createAbstractEntityDetailsForm } from '../abstractForm';`,
      `import { useEntityForm } from '../hooks/useEntityForm';`,
      `import { FIELDS } from '../../entities/${fileName}';`,
      `import type { Entity as ${entityName} } from '../../entities/${fileName}';`,
      `import { ${getDoc}, ${updateDoc} } from '../../generated/operations/${fileName}.generated';`,
      `import type { EntityDetailsFormProps } from '../types';`,
      '',
      `const ${compName}Presentation = createAbstractEntityDetailsForm<${entityName}>(FIELDS);`,
      '',
      `export interface ${compName}Props`,
      `  extends Omit<EntityDetailsFormProps<${entityName}>, 'value' | 'onChange' | 'mode' | 'errors' | 'disabled'> {`,
      `  endpoint: string;`,
      `  headers?: Record<string, string>;`,
      `  getHeaders?: () => Record<string, string> | Promise<Record<string, string>>;`,
      `  netexId?: string;`,
      `  mode?: 'view' | 'edit';`,
      `  onSaved?: (netexId: string) => void;`,
      `  onError?: (generalErrors: string[]) => void;`,
      `}`,
      '',
      `export function ${compName}(props: ${compName}Props) {`,
      `  const { mode = 'edit', layout, variant, slotProps, ...rest } = props;`,
      `  const { value, setValue, loading, saving, errors, handleSave } = useEntityForm<${entityName}>({`,
      `    fields: FIELDS,`,
      `    query: {`,
      `      document: ${getDoc},`,
      `      variables: (netexId) => ({ filter: { netexIds: [netexId], dataOwnerRef: '' } }),`,
      `      resultPath: ['${entry.queryRoot}', 'content', 0] as const,`,
      `    },`,
      `    mutation: {`,
      `      document: ${updateDoc},`,
      `      resultPath: ['${entry.mutationName}'] as const,`,
      `    },`,
      `    ...rest,`,
      `  });`,
      '',
      `  if (loading && !value) return <div>Loading...</div>;`,
      '',
      `  return (`,
      `    <>`,
      `      <${compName}Presentation`,
      `        value={value ?? ({} as ${entityName})}`,
      `        onChange={setValue}`,
      `        mode={mode}`,
      `        layout={layout}`,
      `        variant={variant}`,
      `        slotProps={slotProps}`,
      `        errors={errors}`,
      `        disabled={loading || saving}`,
      `      />`,
      `      {mode === 'edit' && (`,
      `        <button onClick={handleSave} disabled={saving}>Save</button>`,
      `      )}`,
      `    </>`,
      `  );`,
      `}`,
      '',
    ].join('\n');

    const outPath = resolve(OUT_DIR, `${fileName}.tsx`);
    writeFileSync(outPath, src);
    console.log(`[wrapper] ${entityName} → ${outPath}`);
    exports.push(`export { ${compName} } from './${fileName}';`);
  }

  const barrel = [BANNER, ...exports, ''].join('\n');
  writeFileSync(resolve(OUT_DIR, 'index.ts'), barrel);
  console.log(`[wrapper] wrote ${OUT_DIR}/index.ts`);
};

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    main();
  } catch (err) {
    console.error(String(err instanceof Error ? err.message : err));
    process.exit(1);
  }
}
