/**
 * generateDocuments — compile-time step.
 *
 * Builds the per-entity GraphQL operation documents from the real sobek
 * schema (not from regex-parsed TS interfaces). Selection sets are generated
 * with `@graphql-tools/utils.buildOperationNodeForField` and then pruned by
 * policy declared in `entities.manifest.json`.
 *
 * Output: src/generated/operations/documents/<entity>.graphql
 *   - one paged query  : Get<Entity>($filter: <Entity>Filter!)
 *   - one mutation     : Update<Entity>($input: <Entity>Input!)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildSchema, print, visit, OperationTypeNode, type FieldNode, type SelectionNode, type OperationDefinitionNode } from 'graphql';
import { buildOperationNodeForField } from '@graphql-tools/utils';

const MANIFEST = 'entities.manifest.json';
const SCHEMA_FILES = ['./schema/sobek.schema.graphqls', './schema/sobek.patch.graphqls'];
const OUT_DIR = 'src/generated/operations';
const BANNER = '# AUTO-GENERATED by scripts/generateDocuments.ts — do not edit.\n';

/** How deeply `buildOperationNodeForField` expands nested object fields. */
const OPERATION_DEPTH_LIMIT = 3;

/** Paged query always requests the first page with a single result. */
const QUERY_PAGE = 0;
const QUERY_SIZE = 1;

/** Name of the identity leaf used for single-relation references. */
const RELATION_ID_FIELD = 'netexId';

/** Variable / argument names shared between the generated wrapper and the hook. */
const FILTER_VAR = 'filter';
const INPUT_VAR = 'input';

const toCamel = (s: string) => s.charAt(0).toLowerCase() + s.slice(1);

interface ManifestEntry {
  entity: string;
  queryRoot: string;
  mutationName: string;
  ignore?: string[];
  relationFields?: string[];
}

interface ParsedEntry extends ManifestEntry {
  fileName: string;
}

const parseManifest = (): ParsedEntry[] => {
  const entries: ManifestEntry[] = JSON.parse(readFileSync(resolve(MANIFEST), 'utf8'));
  return entries.map(e => ({ ...e, fileName: toCamel(e.entity) }));
};

const buildSchemaFromFiles = () =>
  buildSchema(SCHEMA_FILES.map(f => readFileSync(resolve(f), 'utf8')).join('\n'));

/**
 * Recursively prune the auto-built selection set.
 *
 *   1. Drop any field whose logical path matches an `ignore` entry.
 *   2. Collapse configured relation fields to `{ netexId }` only.
 */
function pruneSelections(
  node: FieldNode,
  path: string[],
  ignore: Set<string>,
  relations: Set<string>
): FieldNode {
  if (!node.selectionSet) return node;

  if (ignore.has(path.join('.'))) {
    return { ...node, selectionSet: { ...node.selectionSet, selections: [] } };
  }

  const selections: SelectionNode[] = [];
  for (const sel of node.selectionSet.selections) {
    if (sel.kind !== 'Field') continue;
    const childPath = [...path, sel.name.value];

    if (ignore.has(childPath.join('.'))) continue;

    if (relations.has(sel.name.value) && sel.selectionSet) {
      selections.push({
        ...sel,
        selectionSet: {
          ...sel.selectionSet,
          selections: sel.selectionSet.selections
            .filter((s): s is FieldNode => s.kind === 'Field' && s.name.value === RELATION_ID_FIELD)
            .map(s => ({ ...s, selectionSet: undefined })),
        },
      });
      continue;
    }

    selections.push(pruneSelections(sel, childPath, ignore, relations));
  }

  return { ...node, selectionSet: { ...node.selectionSet, selections } };
}

/**
 * Fail fast if a configured relation field is present but was truncated by
 * `depthLimit`, leaving no `netexId` selected. Otherwise the wrapper would
 * receive a partial relation object and `toInputEntity` would drop it.
 */
function assertRelationsSelected(
  entry: ParsedEntry,
  node: FieldNode,
  path: string[]
): void {
  const relations = new Set(entry.relationFields ?? []);

  function walk(n: FieldNode, p: string[]): void {
    if (relations.has(n.name.value) && n.selectionSet) {
      const hasNetexId = n.selectionSet.selections.some(
        s => s.kind === 'Field' && s.name.value === RELATION_ID_FIELD
      );
      if (!hasNetexId) {
        throw new Error(
          `[generateDocuments] relation field "${n.name.value}" at ${p.join('.')} was truncated by depthLimit=${OPERATION_DEPTH_LIMIT}; increase the limit or adjust the schema policy for ${entry.entity}`
        );
      }
    }

    if (!n.selectionSet) return;
    for (const sel of n.selectionSet.selections) {
      if (sel.kind === 'Field') walk(sel, [...p, sel.name.value]);
    }
  }

  walk(node, path);
}

const buildQueryDocument = (
  entry: ParsedEntry,
  schema: ReturnType<typeof buildSchema>
): string => {
  const op = buildOperationNodeForField({
    schema,
    kind: OperationTypeNode.QUERY,
    field: entry.queryRoot,
    depthLimit: OPERATION_DEPTH_LIMIT,
  }) as OperationDefinitionNode;

  const rootField = op.selectionSet.selections[0] as FieldNode;
  const ignore = new Set(entry.ignore ?? []);
  const relations = new Set(entry.relationFields ?? []);
  const prunedRoot = pruneSelections(rootField, [entry.queryRoot], ignore, relations);
  assertRelationsSelected(entry, prunedRoot, [entry.queryRoot]);

  const filterType = `${entry.entity}Filter`;
  const opName = `Get${entry.entity}`;

  const transformed = visit(op, {
    OperationDefinition(node) {
      return {
        ...node,
        name: { ...node.name!, value: opName },
        variableDefinitions: [
          {
            kind: 'VariableDefinition',
            variable: { kind: 'Variable', name: { kind: 'Name', value: FILTER_VAR } },
            type: { kind: 'NonNullType', type: { kind: 'NamedType', name: { kind: 'Name', value: filterType } } },
          },
        ],
        selectionSet: {
          ...node.selectionSet,
          selections: [prunedRoot],
        },
      };
    },
    Field(node) {
      if (node.name.value === entry.queryRoot) {
        return {
          ...node,
          arguments: [
            {
              kind: 'Argument',
              name: { kind: 'Name', value: FILTER_VAR },
              value: { kind: 'Variable', name: { kind: 'Name', value: FILTER_VAR } },
            },
            {
              kind: 'Argument',
              name: { kind: 'Name', value: 'page' },
              value: { kind: 'IntValue', value: String(QUERY_PAGE) },
            },
            {
              kind: 'Argument',
              name: { kind: 'Name', value: 'size' },
              value: { kind: 'IntValue', value: String(QUERY_SIZE) },
            },
          ],
        };
      }
    },
  });

  return print(transformed);
};

const buildMutationDocument = (
  entry: ParsedEntry,
  schema: ReturnType<typeof buildSchema>
): string => {
  const inputType = `${entry.entity}Input`;
  const opName = `Update${entry.entity}`;

  const op = buildOperationNodeForField({
    schema,
    kind: OperationTypeNode.MUTATION,
    field: entry.mutationName,
  }) as OperationDefinitionNode;

  const transformed = visit(op, {
    OperationDefinition(node) {
      return {
        ...node,
        name: { ...node.name!, value: opName },
        variableDefinitions: [
          {
            kind: 'VariableDefinition',
            variable: { kind: 'Variable', name: { kind: 'Name', value: INPUT_VAR } },
            type: { kind: 'NonNullType', type: { kind: 'NamedType', name: { kind: 'Name', value: inputType } } },
          },
        ],
      };
    },
  });

  return print(transformed);
};

const buildDocument = (
  entry: ParsedEntry,
  schema: ReturnType<typeof buildSchema>
): string => {
  const query = buildQueryDocument(entry, schema);
  const mutation = buildMutationDocument(entry, schema);
  return [BANNER, query, '\n', mutation, '\n'].join('');
};

const main = (): void => {
  const schema = buildSchemaFromFiles();
  const entries = parseManifest();
  mkdirSync(resolve(OUT_DIR, 'documents'), { recursive: true });

  for (const entry of entries) {
    const out = buildDocument(entry, schema);
    const outPath = resolve(OUT_DIR, 'documents', `${entry.fileName}.graphql`);
    writeFileSync(outPath, out);
    console.log(`[docs] ${entry.entity} → ${outPath}`);
  }
};

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    main();
  } catch (err) {
    console.error(String(err instanceof Error ? err.message : err));
    process.exit(1);
  }
}
