/**
 * generateDocuments — compile-time step.
 *
 * For each manifest entry it reads the committed `src/entities/<entity>.ts`
 * and emits `src/generated/operations/documents/<entity>.graphql` carrying
 * one query + one mutation document.
 *
 * Selection-set rules (derived from the Entity interface in the entity file):
 *   - scalar / enum                → bare field name
 *   - MultilingualString           → `field { lang value }`
 *   - object with `netexId` key    → `field { netexId }` (relation)
 *   - array of identifiable objects → omitted (serverManaged grid)
 *   - identity-less value-object  → recurse into members
 *   - identity-less object array  → omitted
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const MANIFEST = 'entities.manifest.json';
const ENT_DIR = 'src/entities';
const OUT_DIR = 'src/generated/operations';
const BANNER = '# AUTO-GENERATED by scripts/generateDocuments.ts — do not edit.\n';

const toCamel = (s: string) => s.charAt(0).toLowerCase() + s.slice(1);

interface EntityField {
  name: string;
  tsType: string;
  isOptional: boolean;
}

const parseEntityInterface = (src: string): EntityField[] => {
  const match = src.match(/export interface Entity \{([^}]+)\}/s);
  if (!match) return [];
  const body = match[1];
  const lines = body.split('\n').map(l => l.trim()).filter(Boolean);
  return lines.map(line => {
    const m = line.match(/^(\w+)\??\s*:\s*(.+?);?\s*$/);
    if (!m) return null;
    const [, name, tsType] = m;
    return { name, tsType: tsType.replace(/;$/, ''), isOptional: line.includes('?:') };
  }).filter(Boolean) as EntityField[];
};

const toSelection = (field: EntityField): string | null => {
  const t = field.tsType;

  // Array of objects → omit
  if (t.includes('Array<') || t.includes('[')) {
    return null;
  }

  // Value objects with subfields
  if (t.includes('MultilingualString')) {
    return `${field.name} { lang value }`;
  }
  if (t.includes('PassengerCapacity')) {
    return `${field.name} { fareClass totalCapacity seatingCapacity standingCapacity specialPlaceCapacity wheelchairPlaceCapacity pushchairCapacity pramPlaceCapacity bicycleRackCapacity }`;
  }
  if (t.includes('PrivateCode')) {
    return `${field.name} { type value }`;
  }
  if (t.includes('KeyValues')) {
    return `${field.name} { key value }`;
  }

  // Relations → netexId
  if (t.includes('VehicleType') || t.includes('DeckPlan')) {
    return `${field.name} { netexId }`;
  }

  // Scalars, enums, string union types
  return field.name;
};

const buildDocument = (
  entityName: string,
  fields: EntityField[],
  mutationName: string
): string => {
  const selections = fields.map(toSelection).filter(Boolean);

  const queryName = `Get${entityName}`;
  const inputType = `${entityName}Input`;
  const filterType = `${entityName}Filter`;

  return [
    BANNER,
    `query ${queryName}($filter: ${filterType}!) {`,
    `  ${toCamel(entityName)}s(filter: $filter, page: 0, size: 1) {`,
    '    content {',
    ...selections.map(s => `      ${s}`),
    '    }',
    '  }',
    '}',
    '',
    `mutation Update${entityName}($input: ${inputType}!) {`,
    `  ${mutationName}(input: $input)`,
    '}',
    '',
  ].join('\n');
};

const main = (): void => {
  const manifest: (string | { entity: string; mutationName?: string })[] = JSON.parse(
    readFileSync(resolve(MANIFEST), 'utf8')
  );
  mkdirSync(resolve(OUT_DIR, 'documents'), { recursive: true });

  for (const entry of manifest) {
    const entityName = typeof entry === 'string' ? entry : entry.entity;
    const fileName = toCamel(entityName);
    const mutationName =
      (typeof entry === 'object' && entry.mutationName) ||
      `createOrUpdate${entityName}`;

    const entitySrc = readFileSync(resolve(ENT_DIR, `${fileName}.ts`), 'utf8');
    const fields = parseEntityInterface(entitySrc);

    const out = buildDocument(entityName, fields, mutationName);
    const outPath = resolve(OUT_DIR, 'documents', `${fileName}.graphql`);
    writeFileSync(outPath, out);
    console.log(`[docs] ${entityName} → ${outPath}`);
  }
};

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    main();
  } catch (err) {
    console.error(String(err instanceof Error ? err.message : err));
    process.exit(1);
  }
}
