/**
 * generateDocuments — compile-time step.
 *
 * Builds the per-entity GraphQL operation documents from the real sobek
 * schema (not from regex-parsed TS interfaces). Selection sets are generated
 * with `@graphql-tools/utils.buildOperationNodeForField` and then pruned by
 * policy declared in `entities.manifest.json`.
 *
 * Output: src/generated/operations/documents/<entity>.graphql
 *   - one paged query  : Get<Entity>($filter: <Entity>Filter!)
 *   - one mutation     : Update<Entity>($input: <Entity>Input!)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildSchema, isInputObjectType, print, visit, OperationTypeNode, type FieldNode, type SelectionNode, type OperationDefinitionNode } from 'graphql';
import { buildOperationNodeForField } from '@graphql-tools/utils';

const MANIFEST = 'entities.manifest.json';
/**
 * Live schema only — never `schema/sobek.patch.graphqls`. The overlay declares
 * fields sobek has not shipped; feeding it here would put them in a selection
 * set and the backend would reject the query. The patch reaches the form via
 * `codegen.ts` → `sobekTypes.ts` → `distillTypes.ts` alone.
 */
export const SCHEMA_FILES = ['./schema/sobek.schema.graphqls'];
const OUT_DIR = 'src/generated/operations';
const BANNER = '# AUTO-GENERATED by scripts/generateDocuments.ts — do not edit.\n';
const TS_BANNER = '// AUTO-GENERATED by scripts/generateDocuments.ts — do not edit.';

/** Wire-key masks consumed by `useEntityForm` (see `reduceToSobekInput`). */
const KEYS_FILE = 'inputKeys.ts';

/** How deeply `buildOperationNodeForField` expands nested object fields. */
const OPERATION_DEPTH_LIMIT = 3;

/** Paged query always requests the first page with a single result. */
const QUERY_PAGE = 0;
const QUERY_SIZE = 1;

/** Name of the identity leaf used for single-relation references. */
const RELATION_ID_FIELD = 'netexId';

/** Variable / argument names shared between the generated wrapper and the hook. */
const FILTER_VAR = 'filter';
const INPUT_VAR = 'input';

const toCamel = (s: string) => s.charAt(0).toLowerCase() + s.slice(1);

interface ManifestEntry {
  entity: string;
  queryRoot: string;
  mutationName: string;
  ignore?: string[];
  relationFields?: string[];
}

interface ParsedEntry extends ManifestEntry {
  fileName: string;
}

const parseManifest = (): ParsedEntry[] => {
  const entries: ManifestEntry[] = JSON.parse(readFileSync(resolve(MANIFEST), 'utf8'));
  return entries.map(e => ({ ...e, fileName: toCamel(e.entity) }));
};

const buildSchemaFromFiles = () =>
  buildSchema(SCHEMA_FILES.map(f => readFileSync(resolve(f), 'utf8')).join('\n'));

/**
 * Recursively prune the auto-built selection set.
 *
 *   1. Drop any field whose logical path matches an `ignore` entry.
 *   2. Collapse configured relation fields to `{ netexId }` only.
 */
function pruneSelections(
  node: FieldNode,
  path: string[],
  ignore: Set<string>,
  relations: Set<string>
): FieldNode {
  if (!node.selectionSet) return node;

  if (ignore.has(path.join('.'))) {
    return { ...node, selectionSet: { ...node.selectionSet, selections: [] } };
  }

  const selections: SelectionNode[] = [];
  for (const sel of node.selectionSet.selections) {
    if (sel.kind !== 'Field') continue;
    const childPath = [...path, sel.name.value];

    if (ignore.has(childPath.join('.'))) continue;

    if (relations.has(sel.name.value) && sel.selectionSet) {
      selections.push({
        ...sel,
        selectionSet: {
          ...sel.selectionSet,
          selections: sel.selectionSet.selections
            .filter((s): s is FieldNode => s.kind === 'Field' && s.name.value === RELATION_ID_FIELD)
            .map(s => ({ ...s, selectionSet: undefined })),
        },
      });
      continue;
    }

    selections.push(pruneSelections(sel, childPath, ignore, relations));
  }

  return { ...node, selectionSet: { ...node.selectionSet, selections } };
}

/**
 * Fail fast if a configured relation field is missing from the pruned selection
 * set, or is present without its `netexId` leaf. Both states mean the wrapper
 * would receive an entity whose relation is absent or partial and
 * `toInputEntity` would silently drop it.
 *
 * Checks *presence*, not just netexId-within-present: when `depthLimit` truncates
 * a relation, `buildOperationNodeForField` drops the field entirely rather than
 * emitting it netexId-less, so a walk that only inspects nodes already in the
 * tree would never see it. Here we look up each configured relation by name.
 */
function assertRelationsSelected(entry: ParsedEntry, node: FieldNode): void {
  const found = new Map<string, FieldNode>();
  (function collect(n: FieldNode): void {
    if (!n.selectionSet) return;
    for (const sel of n.selectionSet.selections) {
      if (sel.kind !== 'Field') continue;
      found.set(sel.name.value, sel);
      collect(sel);
    }
  })(node);

  for (const rel of entry.relationFields ?? []) {
    const relNode = found.get(rel);
    if (!relNode) {
      throw new Error(
        `[generateDocuments] relation field "${rel}" is absent from the ${entry.entity} selection set — likely truncated by depthLimit=${OPERATION_DEPTH_LIMIT}; increase the limit or adjust the schema policy.`
      );
    }
    const hasNetexId = relNode.selectionSet?.selections.some(
      s => s.kind === 'Field' && s.name.value === RELATION_ID_FIELD
    );
    if (!hasNetexId) {
      throw new Error(
        `[generateDocuments] relation field "${rel}" in ${entry.entity} has no "${RELATION_ID_FIELD}" leaf selected; adjust the schema policy.`
      );
    }
  }
}

const buildQueryDocument = (
  entry: ParsedEntry,
  schema: ReturnType<typeof buildSchema>
): string => {
  const op = buildOperationNodeForField({
    schema,
    kind: OperationTypeNode.QUERY,
    field: entry.queryRoot,
    depthLimit: OPERATION_DEPTH_LIMIT,
  }) as OperationDefinitionNode;

  const rootField = op.selectionSet.selections[0] as FieldNode;
  const ignore = new Set(entry.ignore ?? []);
  const relations = new Set(entry.relationFields ?? []);
  const prunedRoot = pruneSelections(rootField, [entry.queryRoot], ignore, relations);
  assertRelationsSelected(entry, prunedRoot);

  const filterType = `${entry.entity}Filter`;
  const opName = `Get${entry.entity}`;

  const transformed = visit(op, {
    OperationDefinition(node) {
      return {
        ...node,
        name: { ...node.name!, value: opName },
        variableDefinitions: [
          {
            kind: 'VariableDefinition',
            variable: { kind: 'Variable', name: { kind: 'Name', value: FILTER_VAR } },
            type: { kind: 'NonNullType', type: { kind: 'NamedType', name: { kind: 'Name', value: filterType } } },
          },
        ],
        selectionSet: {
          ...node.selectionSet,
          selections: [prunedRoot],
        },
      };
    },
    Field(node) {
      if (node.name.value === entry.queryRoot) {
        return {
          ...node,
          arguments: [
            {
              kind: 'Argument',
              name: { kind: 'Name', value: FILTER_VAR },
              value: { kind: 'Variable', name: { kind: 'Name', value: FILTER_VAR } },
            },
            {
              kind: 'Argument',
              name: { kind: 'Name', value: 'page' },
              value: { kind: 'IntValue', value: String(QUERY_PAGE) },
            },
            {
              kind: 'Argument',
              name: { kind: 'Name', value: 'size' },
              value: { kind: 'IntValue', value: String(QUERY_SIZE) },
            },
          ],
        };
      }
    },
  });

  return print(transformed);
};

const buildMutationDocument = (
  entry: ParsedEntry,
  schema: ReturnType<typeof buildSchema>
): string => {
  const inputType = `${entry.entity}Input`;
  const opName = `Update${entry.entity}`;

  const op = buildOperationNodeForField({
    schema,
    kind: OperationTypeNode.MUTATION,
    field: entry.mutationName,
  }) as OperationDefinitionNode;

  const transformed = visit(op, {
    OperationDefinition(node) {
      return {
        ...node,
        name: { ...node.name!, value: opName },
        variableDefinitions: [
          {
            kind: 'VariableDefinition',
            variable: { kind: 'Variable', name: { kind: 'Name', value: INPUT_VAR } },
            type: { kind: 'NonNullType', type: { kind: 'NamedType', name: { kind: 'Name', value: inputType } } },
          },
        ],
      };
    },
  });

  return print(transformed);
};

const buildDocument = (
  entry: ParsedEntry,
  schema: ReturnType<typeof buildSchema>
): string => {
  const query = buildQueryDocument(entry, schema);
  const mutation = buildMutationDocument(entry, schema);
  return [BANNER, query, '\n', mutation, '\n'].join('');
};

/**
 * Emit the wire-key masks — one keyset per entity, read from the live schema's
 * `<Entity>Input`. `useEntityForm` intersects the form-derived input against
 * these before the request, so a patch-only field can never be sent.
 *
 * The `satisfies` clause is the guard: the keys come from this script's schema
 * read, the type from graphql-codegen's. Feed the patch to either generator and
 * the two disagree, so the build fails instead of the backend.
 *
 * @param entries manifest entries to emit a mask for
 * @param schema  live sobek schema (no patch overlay)
 * @returns source of `src/generated/operations/inputKeys.ts`
 */
export function buildInputKeysModule(
  entries: ParsedEntry[],
  schema: ReturnType<typeof buildSchema>
): string {
  const imports: string[] = [];
  const masks: string[] = [];

  for (const entry of entries) {
    const inputName = `${entry.entity}Input`;
    const type = schema.getType(inputName);
    if (!isInputObjectType(type)) {
      throw new Error(`[generateDocuments] ${inputName} is not an input object type in the live schema.`);
    }
    const keys = Object.keys(type.getFields());
    imports.push(`import type { ${inputName} } from './${entry.fileName}.generated';`);
    masks.push(
      [
        `export const ${inputName}Keys = {`,
        ...keys.map(k => `  ${k}: 1,`),
        `} satisfies Record<keyof ${inputName}, 1>;`,
      ].join('\n')
    );
  }

  return [TS_BANNER, imports.join('\n'), '', masks.join('\n\n'), ''].join('\n');
}

const main = (): void => {
  const schema = buildSchemaFromFiles();
  const entries = parseManifest();
  mkdirSync(resolve(OUT_DIR, 'documents'), { recursive: true });

  for (const entry of entries) {
    const out = buildDocument(entry, schema);
    const outPath = resolve(OUT_DIR, 'documents', `${entry.fileName}.graphql`);
    writeFileSync(outPath, out);
    console.log(`[docs] ${entry.entity} → ${outPath}`);
  }

  const keysPath = resolve(OUT_DIR, KEYS_FILE);
  writeFileSync(keysPath, buildInputKeysModule(entries, schema));
  console.log(`[docs] input keys → ${keysPath}`);
};

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    main();
  } catch (err) {
    console.error(String(err instanceof Error ? err.message : err));
    process.exit(1);
  }
}
