/**
 * generateWrappers — compile-time step.
 *
 * For each manifest entry it reads the committed entity file for `FIELDS` and
 * the generated operation file for document names, then writes a thin
 * `src/EntityDetailsForm/formImpls/<entity>.tsx` smart wrapper component.
 *
 * Manifest policy in `entities.manifest.json` also drives the query root name
 * and the mutation result field so the wrapper stays correct when the naming
 * diverges from `createOrUpdate<Entity>`.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const MANIFEST = 'entities.manifest.json';
const OUT_DIR = 'src/EntityDetailsForm/formImpls';
const BANNER = '// AUTO-GENERATED by scripts/generateWrappers.ts — do not edit.\n';

const toCamel = (s: string) => s.charAt(0).toLowerCase() + s.slice(1);

interface ManifestEntry {
  entity: string;
  queryRoot: string;
  mutationName: string;
  ignore?: string[];
  relationFields?: string[];
}

/**
 * Emit the wrapper component source for one manifest entry. Exported for
 * `generateWrappers.test.ts`, which pins the emitted contract (provider-only
 * session inputs, not-found branch, create-mode dataOwnerRef fallback).
 */
export const renderWrapperSource = (entry: ManifestEntry): string => {
  const entityName = entry.entity;
  const fileName = toCamel(entityName);
  const compName = `${entityName}Form`;

  const getDoc = `Get${entityName}Document`;
  const updateDoc = `Update${entityName}Document`;
  const inputKeys = `${entityName}InputKeys`;

  return [
      BANNER,
      `import { createAbstractEntityDetailsForm } from '../abstractForm';`,
      `import { useEntityForm } from '../hooks/useEntityForm';`,
      `import { useSobekCtx } from '../../context/SobekContext';`,
      `import { FIELDS } from '../../entities/${fileName}';`,
      `import type { Entity as ${entityName} } from '../../entities/${fileName}';`,
      `import { ${getDoc}, ${updateDoc} } from '../../generated/operations/${fileName}.generated';`,
      `import { ${inputKeys} } from '../../generated/operations/inputKeys';`,
      `import type { EntityDetailsFormProps } from '../types';`,
      '',
      `const ${compName}Presentation = createAbstractEntityDetailsForm<${entityName}>(FIELDS);`,
      '',
      `export interface ${compName}Props`,
      `  extends Omit<EntityDetailsFormProps<${entityName}>, 'value' | 'onChange' | 'mode' | 'errors' | 'disabled'> {`,
      `  netexId?: string;`,
      `  mode?: 'view' | 'edit';`,
      `  onSaved?: (netexId: string) => void;`,
      `  onError?: (generalErrors: string[]) => void;`,
      `  /** Every change to the entity, including the load and the post-save refetch.`,
      `   *  Observation only — the form keeps owning its state. */`,
      `  onChange?: (value: ${entityName}) => void;`,
      `  /** Fired when the form crosses between clean and dirty, against the entity`,
      `   *  the server last returned. */`,
      `  onDirtyChange?: (dirty: boolean) => void;`,
      `}`,
      '',
      `export function ${compName}(props: ${compName}Props) {`,
      `  const { mode = 'edit', layout, variant, slotProps, netexId, ...rest } = props;`,
      '  // Display-only: renders the locked dataOwnerRef control. Overlaid on every',
      '  // render, not just while `value` is undefined — otherwise the control keeps',
      '  // showing the org that was current when the user first typed. The write',
      '  // payload and the load filter read context inside the hook; this value',
      '  // never reaches the server from here.',
      `  const { dataOwnerRef } = useSobekCtx();`,
      `  const { value, setValue, loading, saving, load, errors, handleSave } = useEntityForm<${entityName}>({`,
      `    fields: FIELDS,`,
      `    query: {`,
      `      document: ${getDoc},`,
      `      variables: (netexId, dataOwnerRef) => ({ filter: { netexIds: [netexId], dataOwnerRef } }),`,
      `      resultPath: ['${entry.queryRoot}', 'content', 0] as const,`,
      `    },`,
      `    mutation: {`,
      `      document: ${updateDoc},`,
      `      resultPath: ['${entry.mutationName}'] as const,`,
      `      inputKeys: ${inputKeys},`,
      `    },`,
      `    netexId,`,
      `    ...rest,`,
      `  });`,
      '',
      '  // Gate on `load`, not `loading`: LOAD_START only fires from a passive',
      '  // effect, so `loading` is still false on the first commit — gating the',
      '  // not-found branch on it flashed "Not found" on every mount.',
      `  if (netexId && !value && (load === 'idle' || load === 'pending'))`,
      `    return <div>Loading...</div>;`,
      '  // A failed load is not a missing record — keep the two distinguishable.',
      `  if (netexId && load === 'error') return <div>{errors.__init}</div>;`,
      '  // Settled zero-row load: never render a blank editable form (saving it',
      '  // would create a new entity instead of editing one). Guarded on netexId',
      '  // so create mode still renders an empty form.',
      `  if (netexId && !value && load === 'ok') return <div>Not found: {netexId}</div>;`,
      '',
      `  return (`,
      `    <>`,
      `      <${compName}Presentation`,
      `        value={{ ...(value ?? ({} as ${entityName})), dataOwnerRef }}`,
      `        onChange={setValue}`,
      `        mode={mode}`,
      `        layout={layout}`,
      `        variant={variant}`,
      `        slotProps={slotProps}`,
      `        errors={errors}`,
      `        disabled={loading || saving}`,
      `      />`,
      `      {mode === 'edit' && (`,
      `        <button onClick={handleSave} disabled={saving}>Save</button>`,
      `      )}`,
      `    </>`,
      `  );`,
      `}`,
      '',
    ].join('\n');
};

/**
 * Emit the `formImpls/index.ts` barrel.
 *
 * Each entity contributes both its component and its props type: `src/index.ts`
 * re-exports this barrel wholesale, so a type left out here is a type the host
 * has to reconstruct with `ComponentProps<typeof …>`.
 *
 * @param manifest parsed `entities.manifest.json` entries
 * @returns source of `src/EntityDetailsForm/formImpls/index.ts`
 */
export const renderBarrel = (manifest: ManifestEntry[]): string => {
  const lines = manifest.flatMap(entry => {
    const fileName = toCamel(entry.entity);
    const compName = `${entry.entity}Form`;
    return [
      `export { ${compName} } from './${fileName}';`,
      `export type { ${compName}Props } from './${fileName}';`,
    ];
  });
  return [BANNER, ...lines, ''].join('\n');
};

const main = (): void => {
  const manifest: ManifestEntry[] = JSON.parse(readFileSync(resolve(MANIFEST), 'utf8'));
  mkdirSync(resolve(OUT_DIR), { recursive: true });

  for (const entry of manifest) {
    const entityName = entry.entity;
    const fileName = toCamel(entityName);

    const src = renderWrapperSource(entry);

    const outPath = resolve(OUT_DIR, `${fileName}.tsx`);
    writeFileSync(outPath, src);
    console.log(`[wrapper] ${entityName} → ${outPath}`);
  }

  writeFileSync(resolve(OUT_DIR, 'index.ts'), renderBarrel(manifest));
  console.log(`[wrapper] wrote ${OUT_DIR}/index.ts`);
};

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    main();
  } catch (err) {
    console.error(String(err instanceof Error ? err.message : err));
    process.exit(1);
  }
}
